version: "3.4"

services:
  redis:
    image: redis:latest
    networks:
      - dev_network
    expose:
      - 6379
    environment:
      appendonly: "yes"
    volumes:
      - "./tmp/redis-data:/data"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dev_network
    environment:
      - BNET_APPLICATION_ID
      - BNET_APPLICATION_SECRET
      - USE_REDIS=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ".:/api_lib"
    depends_on:
      - redis

networks:
  dev_network: